version: '3.9'

services:
  db:
    image: postgres:17
    container_name: auth-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bench
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: bench
    ports:
      - "8080:8080"

volumes:
  postgres_data: